require("lazy").setup({
  { import = "plugins.nvim-tree" },
  { import = "plugins.telescope" },
  { import = "plugins.nvim-dap" },
  { import = "plugins.mason" },
  { import = "plugins.mason-lspconfig" },
  { import = "plugins.nvim-cmp" },
  { import = "plugins.undotree" },
  { import = "plugins.formatter" },
  { import = "plugins.nvim-treesitter" },
  { import = "plugins.diffview" },
  { import = "plugins.kanagawa" },
  { import = "plugins.nvim-dap-ui" },
  { import = "plugins.toggleterm" },
  { import = "plugins.aerial" },
  { import = "plugins.vim-fugitive" },
  { import = "plugins.render-markdown" },
  { import = "plugins.nvim-ts-autotag" },
  { import = "plugins.nvim-dap-virtual-text" },
  { import = "plugins.copilot" },
  { import = "plugins.copilotchat" },
  { import = "plugins.barbar" },
  -- { import = "plugins.bufferline" },
})
