-- Module to manage keymap notes display
local M = {}

-- Function to jump to a section based on the word under the cursor
function M.jump_to_section()
    -- Get the current line and cursor position
    local line = vim.api.nvim_get_current_line()
    local col = vim.api.nvim_win_get_cursor(0)[2] + 1 -- 1-based column
    local word = vim.fn.expand('<cword>') -- Word under cursor

    -- Try to find a tag like |keymaps-...| in the current line
    local tag = line:match("|(keymaps%-[^|]+)|")
    if not tag then
        -- Fallback to word under cursor if no tag is found in the line
        tag = word:match("^keymaps%-.+$") and word or nil
    end

    if tag then
        -- Search for the matching *keymaps-...* tag
        vim.cmd('silent! /^\\*' .. vim.fn.escape(tag, '-') .. '\\*$')
        vim.cmd('normal! zz') -- Center the screen
    else
        vim.notify("No valid section tag under cursor (word: '" .. word .. "', line: '" .. line .. "', col: " .. col .. ")", vim.log.levels.WARN)
    end
end

-- Function to display keymap notes in a floating window with custom TOC navigation
function M.show_keymaps()
    local lines = {
        "Contents: shortcuts <C-i> jump to link",
        "|keymaps-barbar|            Barbar",
        "|keymaps-dap|               Dap",
        "|keymaps-lsp|               LSP",
        "|keymaps-copilot|           copilot",
        "|keymaps-hyprland|          Hyprland",
        "|keymaps-neovim|            Neovim",
        "|keymaps-gh|                Gh",
        "|keymaps-git|               Git",
        "|keymaps-gitfugitive|       Git Fugitive",
        "|keymaps-comment|           Comment",
        "|keymaps-tmux|              TMUX",
        "|keymaps-printing|          Printing",
        "|keymaps-nvmecli|           Nvmecli",
        "",
        "*keymaps-barbar*",
        "------------------------- Barbar -------------------------",
        "ctrl-p     - pick buffer",
        "alt-,      - previous buffer",
        "alt-.      - next buffer",
        "alt-<      - move left",
        "alt->      - move right",
        "alt-c      - close buffer",
        "alt-p      - pin/unpin buffer",
        "*keymaps-dap*",
        "------------------------- Dap ---------------------------",
        "<leader>dd - start debugging/continue",
        "<leader>b  - set breakpoint",
        "<leader>B  - set conditional breakpoint",
        "<leader>n  - step over",
        "<leader>m  - step into",
        "<leader>p  - step out",
        "<leader>dc - clear breakpoints",
        "*keymaps-lsp*",
        "------------------------- LSP ---------------------------",
        "gD         - jump to declaration",
        "gd         - jump to definition",
        "gi         - jump to implementation",
        "gr         - find references",
        "ctrl-n     - next reference in quickfix",
        "ctrl-p     - previous reference in quickfix",
        "ctrl-k     - show signature help",
        "<leader>rn - rename symbol",
        "<leader>ci - show code actions",
        "<leader>f  - format code",
        "shift-k    - show hover information",
        "<leader>D  - jump to type definition",
        "[d         - go to previous diagnostic",
        "]d         - go to next diagnostic",
        "<leader>q  - add diagnostics to location list",
        "ctrl-j     - next signature",
        "ctrl-k     - previous signature",
        "ctrl-l     - next parameter",
        "ctrl-h     - previous parameter",
        "M-h        - close signature",
        "<leader>wa - Add folder to workspace",
        "<leader>wr - Remove folder from workspace",
        "<leader>wl - List workspace folders",
        "*keymaps-copilot*",
        "------------------------- Copilot ---------------------------",
        "ctrl-h     - dismiss copilot suggestions",
        "ctrl-j     - previous copilot suggestion",
        "ctrl-k     - next copilot suggestion",
        "S-Tab      - accept copilot suggestion",
        "ctrl-j     - CopiltChat previous suggestion",
        "ctrl-k     - CopiltChat next suggestion",
        "S-Tab      - CopiltChat accept suggestion",
        "CR         - CopiltChat submit_prompt normal mode",
        "S-s        - CopiltChat submit_prompt insert mode",
        "<leader>co - CopiltChat toggle normal mode",
        "<leader>co - CopiltChat open visual mode",
        "<leader>cx - CopiltChat reset normal mode",
        "<leader>cs - CopiltChat stop normal mode",
        "<leader>cm - CopiltChat select_model normal mode",
        "<leader>cp - CopiltChat select_prompt normal and visual mode",
        -- "<leader>ca - CopiltChat select_agent normal mode",
        -- "<leader>aq - CopiltChat ask normal and visual mode",
        "*keymaps-hyprland*",
        "------------------------- Hyprland ----------------------",
        "hyprctl reload",
        "Alt + w         - special workspace",
        "Alt + shift + w - send window to special workspace",
        "Alt + a         - change window from tiling window to floating window (hold alt and left mouseclick to drag window)",
        "Alt + print     - screenshot current window",
        "Alt + s         - swap hyprland windows",
        "Alt + x         - toggle hyprland windows",
        "Alt + g         - preset next window to open below i.e. horizontal split",
        "Alt + v         - preset next window to open to the side i.e. vertical split",
        "Alt + d         - open terminal",
        "Alt + shift + e - logout",
        "Alt + r         - resize hyprland window (j,k | h,l) to increment window size",
        "Alt + d         - open bemenu",

        "*keymaps-neovim*",
        "------------------------- Neovim ------------------------",
        "*** Alt + t      - toggleterm",
        "    zo           - zip open",
        "    zc           - zip close",
        "    zR           - open all folds",
        "    zM           - close all folds",
        "    <leader>a    - toggle aerial",
        "            {    - aerial next function",
        "            }    - aerial previous function",
        "    ctrl + a + t - show time in neovim",
        "    ctrl + a + q - show pane numbers",
        "    ctrl + a + o - show all sessions",
        "    ctrl + a + w - show all windows",
        "*** Searching ",
        "    :%s/color/colour/g     # Replaces all 'color' with 'colour' in the file",
        "    :%s/dog/cat/gc         # Replaces all 'dog' with 'cat', but asks first",
        "    :s/red/blue/g          # Replaces all 'red' with 'blue' on current line only",
        "    :%s/hello/hi/gi        # Replaces 'hello', 'HELLO', 'Hello' with 'hi' (case insensitive)",
        "    :5,10s/yes/no/g        # Replaces 'yes' with 'no' between lines 5-10 only",
        "    :.,$s/old/new/g        # Replaces 'old' with 'new' from current line to end",
        "    :%s/const /let /g      # Replaces 'const ' with 'let ' (JavaScript refactor)",
        "    :%s/\t/    /g          # Replaces all tabs with 4 spaces",
        "    :%s/  / /g             # Replaces double spaces with single spaces",
        "    :%s/^#/##/g            # Adds # to all lines starting with # (markdown headers)",
        "*** Treesitter",
        "    :TSInstall {language}              # Install parser for a language",
        "    :TSInstallInfo                     # See installed parsers and their status",
        "    :TSUpdate                          # Update all parsers",
        "    :TSBufToggle highlight             # Toggle highlighting in current buffer",
        "    :TSModuleInfo                      # Show which features are enabled (highlighting, folds, etc.)",
        "*** Lsp",
        "    :LspInfo                           # Show active LSP clients for current buffer",
        "    :LspLog                            # Show LSP log",
        "    :LspRestart                        # Restart LSP client",
        "    :LspStart {server}                 # Start specific language server",
        "    :LspStop                           # Stop LSP client",
        "*** Mason",
        "    :Mason                             # Open Mason UI",
        "    :MasonInstall {name}               # Install specific package",
        "    :MasonUninstall {name}             # Uninstall specific package",
        "    :MasonUpdate                       # Update all packages",
        "    :MasonLog                          # Show Mason's log",
        "*keymaps-gh*",
        "------------------------- Gh ----------------------------",
        "gh --help",
        "gh --version",
        "gh auth login",
        "gh repo list ",
        "gh repo clone owner/repo target-directory",
        "gh repo clone johndoe/my-repo",
        "*keymaps-git*",
        "------------------------- Git ---------------------------",
        ".git/HEAD                                                   - ",
        ".git/refs/heads/                                            - ",
        ".git/refs/remotes/                                          - ",
        ".git/refs/tag/                                              - ",
        ".git/config                                                 - ",
        "*** git remote                                              - list repo remotes",
        "    git remote -v                                           - list repo remotes verbose",
        "    git remote show origin                                  - show information about a remote",
        "    git remote add <name> <url>                             - ",
        "    git remote remove <name>                                - ",
        "*** git branch -D <branch>                                  - FORCE deletes a local branch even if its not fully merged to main master",
        "    git branch -a                                           - ",
        "    git branch -r                                           - ",
        "    git branch                                              - ",
        "    git branch -vv                                          - ",
        "    git branch --set-upstream-to=<remote-name>/<remote-branch>",
        "    git branch --set-upstream-to=origin/branch1             - ",
        "    git branch --set-upstream-to=origin/develop branch1     - sets the upstream branch to pull from (fetch and merge)",
        "*** git push origin <tagname>                               - ",
        "    git push origin -d <branch>                             - delets a branch from the remote repository",
        "    git push --set-upstream origin branch1                  - sets the upstream branch to push to",
        "    git push                                                - ",
        "*** git stash                                               - Stash the current changes in your working directory, allowing you to switch to a clean state",
        "    git stash list                                          - list List all the stashed changes",
        "    git stash apply                                         - Apply the most recently stashed changes to your working directory",
        "    git stash apply <stash-id>                              - Apply a specific stashed change by its ID",
        "    git stash pop                                           - ",
        "    git stash drop                                          - Remove the most recently stashed change",
        "    git stash drop <stash-id>                               - Remove a specific stashed change by its ID",
        "*** git config list                                         - ",
        "    git config list --local                                 - ",
        "    git config list --show-origin                           - ",
        "    git config set <name> <value>                           - ",
        "    git config push.default upstream                        - ",
        "    git config --unset push.default                         - ",
        "    git config --get push.default                           - ",
        "    git config branch.<local-branch>.pushRemote <remote-name> ",
        "    git config branch.<local-branch>.pushBranch <remote-branch>",
        "    git config branch.feature.pushRemote origin               ",
        "    git config branch.feature.pushBranch new-feature          ",
        "*** git rebase <branch>                                     - ",
        "    git rebase -i <commit>                                  - ",
        "    git rebase -i HEAD~3                                    - rebase selecting the last 3 commits",
        "    git rebase --abort",
        "    git rebase main                                         - replays the commits on the current branch ONTO main, after all commits on main",
        "*** git reset <commit>                                      - ",
        "    git reset --soft HEAD^1                                 - ",
        "    git reset --soft HEAD~2                                 - refers to the parent commit history, sets the head to this commit",
        "    git reset --soft HEAD@{2}                               - refers to actions in the reflog, sets the state back to what it was 2 actions ago",
        "    git reset --soft 1abd7afe                               - sets the head to this commit, without discarding changes to the files, i.e. all the changes show up as staged changes ",
        "*** git fetch --prune                                       - ",
        "    git fetch                                               - downloads the latest changes from the remote branches but doesnt apply them to any branch",
        "    git fetch --prune                                       - updates your local repo with the correct remote branches so that when you run git branch -r you wont see any branches that no long exist",
        "*** git restore --staged file1.txt                          - will set the file back to its original state in HEAD (last commit). If the file was untracked it will become untracked again. It will also update the unstaged changes to reflect whats in the working directory",
        "    git restore --staged .                                  - to unstage all files",
        "    git restore file1.txt                                   - will discard the unstaged changes and since the unstaged changes are effectively a snapshot or set of changes since the last staged changes, the working directory or file on disk will be set back to match the staged changes",
        "*** git tag <tagname>                                       - ",
        "    git tag -a <tagname> -m <message>                       - ",
        "    git tag -d <tagname>                                    - ",
        "***********NOTE************ all untracked files will never be considered in a diff they must first be tracked/staged",
        "*** git diff --staged                                       - this will diff all staged changes against the last commit",
        "    git diff                                                - this will diff all unstaged changes against the staged changes",
        "    git diff HEAD                                           - this will diff your working directory against the last commit. The working directory is always equal or ahead of the staging area",
        "*************************************************************",
        "*** git log --graph --all                                   - ",
        "    git log --oneline -10                                   - ",
        "*** git commit -m 'mymessage'                               - Create a new commit with the staged changes and provide a commit message",
        "    git commit --amend                                      - ",
        "*** git diff-tree --no-commit-id --name-only -r 1586817     - list the files in a commit",
        "    git diff-tree --no-commit-id --name-only -r HEAD        - list the files in the commit the HEAD is pointing to",
        "*** git merge <branch>                                      - ",
        "    git merge --ff-only <branch-name>                       - merge the branch into the currently checked out branch only if the branch current branch can be fast forwarded, no commits have been made to the current branch since <branch-name> branched off of it",
        "*** git checkout <branch> <tag> <remotebranch> <commithash> - use one of these, the last three are readonly and create a detached head state",
        "    git checkout -b newbranch origin/master                 - ",
        "    git clone <repository>                                  - ",
        "    git init                                                - ",
        "    git status                                              - ",
        "    git add .                                               - ",
        "    git add file1.txt                                       - will track the file and add it to the staging area",
        "    git show <commit>                                       - ",
        "    git revert <commit>                                     - ",
        "    git clean -fdn                                          - force (f) directories (d) dry run (n) removes all untracked files and directories",
        "    git clean -f                                            - removes all untracked files",
        "    git pull --rebase                                       - ",
        "    git pull                                                - Fetch and merge changes from the remote repository into your current branch",
        "    git rev-parse <tag>                                     - ",
        "    git reflog expire --expire=now --all                    - empties the reflog and causes dangling commits to be created",
        "    git gc --prune=now                                      - runs garbage collection with the specific option to immediately delete any unreachable objects such as dangling commits",
        "    git gc                                                  - runs garbage collection using default settings",
        "    git fsck --dangling                                     - list dangling commits",
        "    git reflog                                              - reference log, shows git secret diary",
        "*keymaps-gitfugitive*",
        "------------------------- Git Fugitive ------------------",
        "*** Git Fugitive Quick Reference",
        "    ## Basic Commands",
        "    :G                                 # Open git status window",
        "    :G blame                           # Show git blame",
        "    :G commit                          # Create commit",
        "    :G push                            # Push changes",
        "    :G pull                            # Pull changes",
        "    ## In Status Window(:G)",
        "    s                                  # Stage/unstage file under cursor",
        "    u                                  # Unstage file under cursor",
        "    cc or C                            # Create commit",
        "    =                                  # Toggle inline diff",
        "    dd                                 # See file diff",
        "    ## Common Operations               ",
        "    :G log                             # View git log",
        "    :G diff                            # Show changes in split view",
        "    :G branch                          # List/manage branches",
        "    :G checkout                        # Switch branches",
        "    :G merge                           # Merge branches",
        "    ## Navigation in Diff View",
        "    do                                 # Get changes (diff obtain)",
        "    dp                                 # Put changes (diff put)",
        "    [c                                 # Previous change",
        "    ]c                                 # Next change",
        "    ## Simple Workflow",
        "    1. :G                              # Check status",
        "    2. s                               # Stage files",
        "    3. cc                              #Write commit",
        "    4. :wq                             # Save and finish commit",
        "    5. :G push                         # Push changes",
        "*keymaps-comment*",
        "------------------------- Comment -----------------------",
        "*** NORMAL mode:",
        "    gcc     - toggle comment current line",
        "    gc2j    - toggle comment 2 lines down",
        "    gc4k    - toggle comment 4 lines up",
        "    gcw     - toggle comment word",
        "    gcip    - toggle comment inner paragraph",
        "    gcap    - toggle comment around paragraph",
        "    VISUAL mode:",
        "    gc      - toggle comment selection",
        "    gb      - toggle block comment",
        "    Examples for multi-line:",
        "    3gcc            # toggle comment 3 lines",
        "    gcip            # toggle comment inner paragraph",
        "    gc4j            # toggle comment 4 lines down",
        "    gc5k            # toggle comment 5 lines up",
        "*keymaps-tmux*",
        "------------------------- TMUX --------------------------",
        "   ctrl + a + : - tmux command mode (kill-session)",
        "   ctrl-a, ctrl-s         # Save tmux session",
        "   ctrl-a, ctrl-r         # Reopen last tmux session",
        "   # tmux Quick Reference Sheet - USE Ctrl-a since the .tmux.conf has overridden the default key binding",
        "   # COMMAND MODE (ctrl-b :)",
        "   new                    # New session",
        "   new -s name            # New session with name",
        "   kill-session           # Kills current session",
        "   rename-session         # Renames current session",
        "   ## Session Management",
        "   tmux                   # Start new session",
        "   tmux new -s name       # Start new named session",
        "   tmux ls                # List sessions",
        "   tmux attach -t name    # Attach to named session",
        "   tmux kill-session -t name  # Kill named session",
        "   tmux kill-server       # kill all sessions",
        "   tmux new-session -d -s 'my-session' -c '~/personal'",
        "   tmux switch-client -t 0",
        "   tmux list-keys",
        "   Ctrl-b :               # command mode ex. list-commands list-keys new-session help",
        "   Ctrl-b )               # switch session",
        "   Ctrl-b (               # switch session",
        "   Ctrl-b w               # choose-tree sessions",
        "   ## Windows (tabs)",
        "   Ctrl-b c               # Create window",
        "   Ctrl-b w               # List windows",
        "   Ctrl-b n               # Next window",
        "   Ctrl-b p               # Previous window",
        "   Ctrl-b f               # Find window",
        "   Ctrl-b ,               # Name window",
        "   Ctrl-b &               # Kill window",
        "   Ctrl-b <number>        # Switch to window number",
        "   ## Panes (splits)",
        "   Ctrl-b v               # Vertical split",
        "   Ctrl-b s               # Horizontal split",
        "   Ctrl-b o               # Switch focus between panes",
        "   Ctrl-b q               # Show pane numbers",
        "   Ctrl-b x               # Kill pane",
        "   Ctrl-b +               # Break pane into window",
        "   Ctrl-b -               # Restore pane from window",
        "   Ctrl-b ⍽               # Space - toggle between layouts",
        "   Ctrl-b q               # Show pane numbers",
        "   Ctrl-b {               # Move current pane left",
        "   Ctrl-b }               # Move current pane right",
        "   ## Misc",
        "   Ctrl-b d               # Detach from session",
        "   Ctrl-b t               # Big clock",
        "   Ctrl-b ?               # List all bindings",
        "   Ctrl-b :               # Prompt",
        "   ## Copy Mode",
        "   Ctrl-b [               # Enter copy mode",
        "   q                      # Quit mode",
        "   /                      # Search forward",
        "   ?                      # Search backward",
        "   n                      # Next search match",
        "   N                      # Previous search match",
        "   Space                  # Start selection",
        "   Esc                    # Clear selection",
        "   Enter                  # Copy selection",
        "   Ctrl-b ]               # Paste contents of buffer_0",
        "   ## Navigation",
        "   <C-h>          - switch to left pane    - use <C-a>h to escape vim",
        "   <C-j>          - switch to bottom pane  - use <C-a>j to escape vim",
        "   <C-k>          - switch to top pane     - use <C-a>k to escape vim",
        "   <C-l>          - switch to right pane   - use <C-a>l to escape vim",
        "   ## IRC ##",
        "   /help server",
        "   /fset irc.*",
        "   /set irc.server.libera.chat.sasl_username null",
        "                   88888<>88888",
        "",
        "*keymaps-printing*",
        "------------------------- Printing --------------------------",
        "sudo pacman -S cups cups-filter avahi nss-mdns ghostscript",
        "yay -S epson-inkjet-printer-escpr epson-inkjet-printer-escpr2",
        "/etc/nsswitch.conf - Change host line to 'hosts: files mymachines mdns4_minimal [NOTFOUND=return] dns myhostname'",
        "http://localhost:613",
        "avahi-browse -a",
        "lpstat -p -d",
        "lpinfo -v",
        "lp -o page-left=36 your_label.pdf",
        "/usr/share/ppd/epson-inkjet-printer-escpr                           - File path to PPDs",
        "sudo systemctl enable --now cups                                    - Enables the CUPS service to start automatically upon system boot and initiates it immediately, ensuring the printing system is persistently available",
        "sudo systemctl enable --now avahi-daemon                            - Enables and starts the Avahi daemon for ongoing network discovery of printers and other devices, complementing your mDNS configuration",
        "sudo lpadmin -p PrinterName -E -v device-uri -m driver/ppd/file.ppd - Adds a printer manually via the command line, specifying its name, enabling it (-E), connection URI (from lpinfo -v), and PPD file path (e.g., from your Epson drivers)",
        "lpoptions -d PrinterName                                            - Sets the specified printer as the default for print jobs, streamlining usage when multiple printers are configured",
        "lpq                                                                 - Displays the current print queue, showing pending or active jobs, which aids in monitoring and managing print tasks",
        "lpstat -t                                                           - Provides a comprehensive status overview of the entire printing system, including printers, classes, and jobs",
        "journalctl -u cups                                                  - Retrieves logs specific to the CUPS service for error analysis and debugging, with options like -f for real-time monitoring",
        "avahi-browse -a                                                     - Lists all available network services detected by Avahi, including printers, to confirm discovery and connectivity",
        "avahi-browse _ipp._tcp --resolve                                    - browse targeting IPP printers",
        "cupsctl --debug-logging (executed with sudo)                        - Activates detailed debug logging in CUPS, facilitating in-depth troubleshooting of filtering or rendering issues",
        "sudo usermod -aG lp $USER                                           - Adds the current user to the lp group, granting necessary permissions for print operations without constant sudo usage (requires logout and login to take effect)",
        "cancel -a                                                           - Cancels all jobs in the print queue, useful for clearing stalled or unnecessary tasks",
        "cupsenable PrinterName or cupsdisable PrinterName                   - Resumes or pauses printing on a specific printer, allowing control over device availability",
        "echo 'Test page' | lp                                               - Sends a simple text string as a test print job, verifying basic functionality without needing a file",
        "",
        "*keymaps-nvmecli*",
        "------------------------- Nvmecli --------------------------",
        "pacman -S nvme-cli            - ",
        "nvme list                     - ",
        "nvme format /dev/nvme1n1 -s 1 - ",
        "nvme id-ctrl /dev/nvme1n1 -H  - Query controller information sanicap (Sanitize Capabilities)",
        "nvme id-ns /dev/nvme1n1       - check nuse: 0",
        "nvme sanitize /dev/nvme1n1 -a 2 - Block Erase",
        "nvme sanitize /dev/nvme1n1 -a 4 - Crypto Erase The process may take from seconds (Crypto Erase) to hours (Block Erase), depending on drive size",
        "nvme sanitize-log /dev/nvme1n1- ",
        "-------------------------------------------------------------",
        "n  <Space>ci   *@<Lua 384: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:1222>",
        "n  <Space>rn   *@<Lua 383: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:643>",
        "n  <Space>?    * <Lua 252: ~/source/repos/linux/config/nvim/init.lua:16>",
        "n  <Space>gw   * :Gwrite<CR>",
        "n  <Space>gd   * :Gdiffsplit<CR>",
        "n  <Space>gl   * :Glog<CR>",
        "n  <Space>gp   * :Git push<CR>",
        "n  <Space>gc   * :Gcommit<CR>",
        "n  <Space>gs   * :G<CR>",
        "n  <Space>Fo   * :FormatWrite<CR>",
        "n  <Space>fo   * :Format<CR>",
        "n  <Space>dt   * :DiffviewToggleFiles<CR>",
        "n  <Space>dc   * :DiffviewClose<CR>",
        "n  <Space>do   * :DiffviewOpen<CR>",
        "n  <Space>e    * :NvimTreeToggle<CR>",
        "n  <Space>u    * :UndotreeToggle<CR>",
        "n  <Space>x    * :q<CR>",
        "n  <Space>qc   * <Cmd>cclose<CR>",
        "n  <Space>qo   * <Cmd>copen<CR>",
        "n  <Space>h    * :nohlsearch<CR>",
        "n  <Space>n    * <Lua 33: ~/.config/nvim/lua/core/options.lua:89>",
        "n  <Space>a    * <Lua 88: ~/.local/share/nvim/site/pack/lazy/start/lazy.nvim/lua/lazy/core/handler/keys.lua:121>",
        "n  <Space>dr   * <Lua 101: ~/.config/nvim/lua/plugins/nvim-dap.lua:259>",
        "n  <Space>B    * <Lua 100: ~/.config/nvim/lua/plugins/nvim-dap.lua:258>",
        "n  <Space>c    * <Lua 99: ~/.config/nvim/lua/plugins/nvim-dap.lua:257>",
        "n  <Space>b    * <Lua 98: ~/.config/nvim/lua/plugins/nvim-dap.lua:256>",
        "n  <Space>de   * <Lua 233: ~/.config/nvim/lua/plugins/nvim-dap-ui.lua:17>",
        "n  <Space>s    * :w<CR>",
        "n  <Space>/    * <Lua 149: ~/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:546>",
        "n  <Space>fh   * <Lua 148: ~/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:546>",
        "n  <Space>fb   * <Lua 147: ~/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:546>",
        "n  <Space>fg   * <Lua 146: ~/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:546>",
        "n  <Space>ff   * <Lua 145: ~/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:546>",
        "----------------------------------------------",
        "n  <Space>q    *@<Lua 389: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:2445>",
        "n  <Space>D    *@<Lua 374: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:298>",
        "n  <Space>f    *@<Lua 385: ~/.config/nvim/lua/plugins/mason-lspconfig.lua:32>",
        "n  [<Space>    * <Lua 59: vim/_defaults.lua:0>",
        "n  ]<Space>    * <Lua 60: vim/_defaults.lua:0>",
        "n  <Space>l    * :e<CR>",
        "n  <Space>mu   * <Lua 34: ~/.config/nvim/lua/core/options.lua:111>",
        "n  <Space>f    * :NvimTreeFindFile<CR>",
        "n  <Space>wl   *@<Lua 382: ~/.config/nvim/lua/plugins/mason-lspconfig.lua:26>",
        "n  <Space>wr   *@<Lua 381: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:989>",
        "n  <Space>wa   *@<Lua 380: /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:968>",
        "x  <Space>sr   *@<Lua 353: ~/.local/share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/incremental_selection.lua:127>",
        "x  <Space>se   *@<Lua 352: ~/.local/share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/incremental_selection.lua:59>",
        "n  <Space>ss   *@<Lua 351: ~/.local/share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/incremental_selection.lua:15>",
        "x  <Space>sb   *@<Lua 350: ~/.local/share/nvim/lazy/nvim-treesitter/lua/nvim-treesitter/incremental_selection.lua:59>",
    }
    -- Create buffer
    local buf = vim.api.nvim_create_buf(false, true)
    if not buf then
        vim.notify("Failed to create buffer for keymap window", vim.log.levels.ERROR)
        return
    end

    -- Set buffer content and options
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
    vim.api.nvim_buf_set_option(buf, 'modifiable', false)
    vim.api.nvim_buf_set_option(buf, 'buftype', 'nofile')
    --vim.api.nvim_buf_set_option(buf, 'wrap', false)

    -- Calculate window size
    local max_line_length = 0
    for _, line in ipairs(lines) do
        max_line_length = math.max(max_line_length, #line)
    end
    local width = vim.api.nvim_get_option('columns')
    local height = vim.api.nvim_get_option('lines')
    local win_height = math.min(#lines + 2, math.floor(height * 0.8))
    local win_width = math.min(max_line_length + 2, math.floor(width * 0.9))
    local row = math.ceil((height - win_height) / 2 - 1)
    local col = math.ceil((width - win_width) / 2)

    -- Open floating window
    local win = vim.api.nvim_open_win(buf, true, {
        relative = 'editor',
        width = win_width,
        height = win_height,
        col = col,
        row = row,
        style = 'minimal',
        border = 'rounded',
        noautocmd = true,
    })
    if not win then
        vim.notify("Failed to open keymap window", vim.log.levels.ERROR)
        return
    end

    -- Set buffer-local keymaps
    vim.api.nvim_buf_set_keymap(buf, 'n', '<Esc>', ':close<CR>', { noremap = true, silent = true })
    vim.api.nvim_buf_set_keymap(buf, 'n', 'q', ':close<CR>', { noremap = true, silent = true })
    vim.api.nvim_buf_set_keymap(buf, 'n', '<C-i>', ':lua require("core.keymaps").jump_to_section()<CR>', { noremap = true, silent = true })

    -- Set window options and position cursor
    vim.api.nvim_win_set_option(win, 'scrolloff', 0)
    vim.api.nvim_win_set_cursor(win, {1, 0}) -- Start at TOC
    vim.api.nvim_win_set_option(win, 'relativenumber', true)
    vim.api.nvim_win_set_option(win, 'wrap', false)
end

-- Bind to <leader>?
vim.keymap.set('n', '<leader>?', M.show_keymaps, { desc = 'Show keymap notes with custom TOC navigation' })

return M
