
#preload = ~/source/repos/Linux/config-new-2025/terry-vlisidis-WsEbnsnKbUE-unsplash.jpg
#wallpaper = eDP-1,~/source/repos/Linux/config-new-2025/terry-vlisidis-WsEbnsnKbUE-unsplash.jpg
#preload = $HOME/wallpaper/pexels-iriser-1366957.jpg
#wallpaper = eDP-1, $HOME/wallpaper/pexels-iriser-1366957.jpg


# /usr/share/blackarch/artwork/wallpaper/wallpaper-fog.jpg
# /usr/share/blackarch/artwork/wallpaper/wallpaper-cyberpunk.png
# /usr/share/blackarch/artwork/wallpaper/Green_and_black.png

preload = /usr/share/blackarch/artwork/wallpaper/wallpaper-cyberpunk.png 
wallpaper = eDP-1, /usr/share/blackarch/artwork/wallpaper/wallpaper-cyberpunk.png
